---
title: "Data Analysis"
author: "Ina Liao"
date: "2024-04-10"
output: html_document
---
```{r Setup, include=FALSE}
knitr:::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=FALSE,fig.align = "center", dev = "cairo_pdf", fig.pos = "H")
```

```{r Install packages, message=FALSE}
#install.packages("lubridate")
#install.packages("ggplot2")
#install.packages("forecast")
#install.packages("here")
#install.packages("knitr")
#install.packages("kableExtra")
#install.packages("dplyr")
#install.packages("openxlsx")
#install.packages("ggthemes")
#install.packages("tidyr")
#install.packages("GGally")
#install.packages("tseries")
#install.packages("blorr")
#install.packages("car")
#install.packages("corrplot")
#install.packages("dlm")
#install.packages("randomForest")
#install.packages("Kendall")
library(lubridate)
library(ggplot2)
library(forecast) 
library(here)
library(knitr)
library(kableExtra)
library(dplyr)
library(openxlsx)
library(ggthemes)
library(tidyr)
library(Kendall)
library(GGally)
library(trend)
library(tseries)
library(blorr)   
library(lmtest) 
library(car)
library(cowplot)
library(corrplot)
```

```{r Import Data, echo=TRUE, results='hide'}
here()
raw_water<-read.csv(here('Data/Processed/groundwater_processed.csv'),stringsAsFactors = TRUE,skip=0,header=TRUE)
raw_preci<-read.csv(here('Data/Processed/preci_processed.csv'),stringsAsFactors = TRUE,skip=0,header=TRUE)
raw_temp<-read.csv(here('Data/Processed/temp_processed.csv'),stringsAsFactors = TRUE,skip=0,header=TRUE)

raw_water<-raw_water[,2:10]
raw_preci<-raw_preci[,2:3]
raw_temp<-raw_temp[,2:3]
```

```{r Data Wrangling}
#date format 
raw_water$Date<-ymd(raw_water$Date)
raw_temp$Date<-ymd(raw_temp$Date)
raw_preci$Date<-ymd(raw_preci$Dat)

#daily average 
df_water<-raw_water %>%
  group_by(Date) %>%
  summarize(water=mean(Groundwater_level, na.rm=TRUE)) 

#check timeframe 
print(head(df_water$Date,1)) #1993-02-01
print(tail(df_water$Date,1)) #2022-01-26
print(head(raw_temp$Date,1)) #1990-01-01
print(tail(raw_temp$Date,1)) #2024-03-01

#monthly average 
df_water_monthly<-df_water %>%
  group_by(month=format(Date, "%Y-%m")) %>%
  summarize(monthly_avg = mean(water, na.rm = TRUE))


#merge precipitation dataframe and temperature dataframe 
raw_temp_preci<-left_join(raw_temp,raw_preci,by="Date")

#missing data
#create time dataframe
start_time<-ymd("1993-02-01")
end_time<-ymd("2022-01-26")
df_time_daily<-data.frame(Date=seq(from=start_time, to=end_time, by="1 day"))
df_time_monthly<-data.frame(Date=seq(from=start_time, to=end_time, by="1 month"))

#merge dataframe
df_water_merge<-left_join(df_time_daily,df_water,by="Date")
df_temp_preci_merge<-left_join(df_time_monthly,raw_temp_preci,by="Date")
head(df_water_merge)
head(df_temp_preci_merge)

#filter missing data
df_water_missing<-df_water_merge %>%
  filter(is.na(water))  #continuous data since 2001-03-01
df_temp_preci_merge %>%
  filter(is.na(Temperature)) #no missing value 

#drop the missing value 
df_water<-df_water_merge %>%
  filter(Date>=ymd("2001-03-01") & Date<=ymd("2021-10-22"))
df_temp_preci<-df_temp_preci_merge %>%
  filter(Date>=ymd("2001-03-01")& Date<=ymd("2021-10-22"))

#water is daily data
#temp and preci are monthly data
```



```{r Create time series object}
#monthly average 
df_water_monthly<-df_water %>%
  group_by(month=format(Date, "%Y-%m")) %>%
  summarize(monthly_avg = mean(water, na.rm = TRUE))
df_water_monthly$month<-ym(df_water_monthly$month)

#water
msts_water<-msts(df_water[,2],seasonal.periods=c(7,365),start =c(2001,03), end=c(2021,10))
ts_water_monthly_before<-ts(df_water_monthly[,2], frequency=12,start =c(2001,03), end=c(2021,10))
autoplot(msts_water)
autoplot(ts_water_monthly_before)+
  ggtitle("Monthly groundwater level from March 2001 to October 2021")+
  labs(y="feet",x="")+
  theme(plot.title = element_text(hjust = 0.5))

df_water_monthly<-df_water_monthly %>%
  filter(month>=as.Date("2002-02-01"))
ts_water_monthly<-ts(df_water_monthly[,2], frequency=12,start =c(2002,02), end=c(2021,10))
autoplot(ts_water_monthly)+
  ggtitle("Monthly groundwater level from February 2002 to October 2021")+
  labs(y="feet",x="")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r ACF and PACF}

#water
par(mfrow=c(1,2))
Acf(ts_water_monthly,lag.max=40,main=paste("ACF of Groundwater"),ylim=c(-0.5,1)) 
Pacf(ts_water_monthly,lag.max=40,main=paste("PACF of Groundwater"),ylim=c(-0.5,1))
plot_grid(
  autoplot(ts_water_monthly),
  autoplot(Acf(ts_water_monthly,plot=FALSE,lag.max=40)),
  autoplot(Pacf(ts_water_monthly,plot=FALSE,lag.max=40)),
  nrow=1
)
```
```{r Outliers}

clean_water<-tsclean(ts_water_monthly)
autoplot(clean_water, series="Clean") +
  autolayer(ts_water_monthly, series="Original") +
  labs(title="Groundwater Level", y="feet")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r Detrend and deseason}
#decompose 
water_decompose<-decompose(ts_water_monthly)
plot(water_decompose)

#deseason
water_deseason<-seasadj(water_decompose)
plot_grid(
  autoplot(water_deseason),
  autoplot(Acf(water_deseason,plot=FALSE,lag.max=40)),
  autoplot(Pacf(water_deseason,plot=FALSE,lag.max=40)),
  nrow=1
)
par(mfrow=c(1,2))
Acf(water_deseason,lag.max=40,main=paste("ACF for Groundwater"),ylim=c(-0.5,1)) 
Pacf(water_deseason,lag.max=40,main=paste("PACF for Groundwater"),ylim=c(-0.5,1))
```

```{r Stationary test}
#ts; monthly 
#Mann-Kendall
summary(MannKendall(water_deseason))
#does not reject the null hypothesis, supporting the series is stationary 

#seasonal Mann-Kendall
#correction: calculate monthly average 
trend::smk.test(water_deseason) 
#does not reject the null hypothesis, supporting the series is stationary 

#ADF test
print(adf.test(water_deseason,alternative = "stationary")) 
#does not reject the null hypothesis, the series might contain a unit root
```

```{r Differencing}
#ts; monthly
#find out how many times is needed for differencing 
ns_diff<-nsdiffs(water_deseason)
cat("Number of seasonal differencing needed:", ns_diff) #no need to difference the series
#question: does not need to difference the series but has trend in the data
```

```{r Training and testing}
#water
#from 2001-03-01 to 2021-10-22

#monthly ts
ts_training<-ts(df_water_monthly[,2],
                frequency=12,
                start=c(2002,02), end=c(2020,09))


ts_testing<-ts(df_water_monthly[,2],
               frequency=12,
               start=c(2020,10), end=c(2021,10))
```


```{r ETS}
ETS_fit<-stlf(ts_training,h=12)
```

```{r ARIMA and Fourier terms}
#K=c(2)
#fit ARIMA with deseason time series 
ARIMA_Four_fit_1<-auto.arima(ts_training,
                             seasonal=FALSE, 
                             xreg=fourier(ts_training,K=c(2)))
#forecast with ARIMA_fit
ARIMA_Four_forecast_1<-forecast(ARIMA_Four_fit_1,
                                xreg=fourier(ts_training,K=c(2),h=12),
                                h=12) 
#K=c(4)
#fit ARIMA with deseason time series 
ARIMA_Four_fit_2<-auto.arima(ts_training,
                             seasonal=FALSE, 
                             xreg=fourier(ts_training,K=c(4)))
#forecast with ARIMA_fit
ARIMA_Four_forecast_2<-forecast(ARIMA_Four_fit_2,
                                xreg=fourier(ts_training,K=c(4),h=12),
                                h=12) 

#K=c(6)
#fit ARIMA with deseason time series 
ARIMA_Four_fit_3<-auto.arima(ts_training,
                             seasonal=FALSE, 
                             xreg=fourier(ts_training,K=c(6)))
#forecast with ARIMA_fit
ARIMA_Four_forecast_3<-forecast(ARIMA_Four_fit_3,
                                xreg=fourier(ts_training,K=c(6),h=12),
                                h=12) 
```

```{r exogenous variable}
#temp
#create time series object 
df_temp_preci<-df_temp_preci %>%
  filter(Date>=as.Date("2002-02-01"))

ts_temp_training<-ts(df_temp_preci[,2], frequency=12,
                     start=c(2002,02), end=c(2020,09))

ts_temp_testing<-ts(df_temp_preci[,2], frequency=12,
                     start=c(2020,10), end=c(2021,10))

#preci
#create time series object 
ts_preci_training<-ts(df_temp_preci[,3], frequency=12,
                      start=c(2002,02), end=c(2020,09))

ts_preci_testing<-ts(df_temp_preci[,3], frequency=12,
                     start=c(2020,10), end=c(2021,10))

ts_temp<-ts(df_temp_preci[,2], frequency=12,start=c(2002,02), end=c(2021,10))
ts_preci<-ts(df_temp_preci[,3], frequency=12,start=c(2002,02), end=c(2021,10))
autoplot(ts_temp)+
  ggtitle("Monthly temperature from February 2002 to October 2021")+
  labs(y="°F",x="")+
  theme(plot.title = element_text(hjust = 0.5))
autoplot(ts_preci)+
  ggtitle("Monthly temperature from February 2002 to October 2021")+
  labs(y="mm",x="")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r Correlation Test}
#correlation test 
cor_water_temp<-cor.test(ts_water_monthly,ts_temp,method = "spearman",exact = FALSE)
cor_water_preci<-cor.test(ts_water_monthly,ts_preci,method = "spearman",exact = FALSE)


#create a summary table 
summary_table_cor<-data.frame(
  Variable = c("Temperature", "Precipitation"),
  Correlation_Coefficient = round(c(cor_water_temp$estimate, 
                                    cor_water_preci$estimate), 5),
  P_Value = round(c(cor_water_temp$p.value, 
                    cor_water_preci$p.value), 5)
)

print(summary_table_cor)
```

```{r Sumamry Statistics}
summary_stat<-data.frame(
  Variable=c("Groundwater","Temperature","Precipitation"),
  Mean=round(c(mean(ts_water_monthly),
        mean(ts_temp),
        mean(ts_preci)),4),
  Std_Dev=round(c(sd(ts_water_monthly),
        sd(ts_temp),
        sd(ts_preci)),4),
  Median=round(c(mean(ts_water_monthly),
        mean(ts_temp),
        mean(ts_preci)),4),
  min=round(c(min(ts_water_monthly),
        min(ts_temp),
        min(ts_preci)),4),
  Pctl_25=round(c(quantile(ts_water_monthly,0.25),
        quantile(ts_temp,0.25),
        quantile(ts_preci,0.25)),4),
  Pctl_75=round(c(quantile(ts_water_monthly,0.75),
        quantile(ts_temp,0.75),
        quantile(ts_preci,0.75)),4),
  Max=round(c(max(ts_water_monthly),
        max(ts_temp),
        max(ts_preci)),4)
  
)
summary_stat


```


```{r ARIMA + Fourie + exogenous variable}
#decide not to use the exogenous variable 

#K=c(2)
#fit ARIMA with deseason time series 
ARIMA_Four_fit_XREG_1<-auto.arima(ts_training,
                                  seasonal=FALSE,
                                  #combine fourier and exogenous variable time series  
                                  xreg=as.matrix(cbind(fourier(ts_training,K=c(2)),
                                                       ts_temp_training)))  

#generate fourier terms
fourier_terms_1<-fourier(ts_training, K=c(2), h=12)
#generate forecast
temp_forecast_1<-forecast(ts_temp_training, h=12)
#combine fourier terms and forecasts into a numeric matrix
xreg_matrix_1<-as.matrix(cbind(fourier_terms_1, temp_forecast_1$mean))

#forecast with ARIMA_fit_XREG
ARIMA_Four_forecast_XREG_1<-forecast(ARIMA_Four_fit_XREG_1,
                                     xreg=xreg_matrix_1,
                                     h=12)


#K=c(4)
#fit ARIMA with deseason time series 
ARIMA_Four_fit_XREG_2<-auto.arima(ts_training,
                                  seasonal=FALSE,
                                  xreg=as.matrix(cbind(fourier(ts_training,K=c(4)),
                                                       ts_temp_training)))  


#generate fourier terms
fourier_terms_2<-fourier(ts_training, K=c(4), h=12)
#generate forecast
temp_forecast_2<-forecast(ts_temp_training, h=12)
#combine fourier terms and forecasts into a numeric matrix
xreg_matrix_2<-as.matrix(cbind(fourier_terms_2, temp_forecast_2$mean))

#forecast with ARIMA_fit_XREG
ARIMA_Four_forecast_XREG_2<-forecast(ARIMA_Four_fit_XREG_2,
                                     xreg=xreg_matrix_2,
                                     h=12)

#K=c(6)
#fit ARIMA with original time series 
ARIMA_Four_fit_XREG_3<-auto.arima(ts_training,
                                  seasonal=FALSE,
                                  #combine fourier and exogenous variable time series  
                                  xreg=as.matrix(cbind(fourier(ts_training,K=c(6)),
                                                       ts_temp_training)))  

#generate fourier terms
fourier_terms_3<-fourier(ts_training, K=c(6), h=12)
#generate forecast
temp_forecast_3<-forecast(ts_temp_training, h=12)
#combine fourier terms and forecasts into a numeric matrix
xreg_matrix_3<-as.matrix(cbind(fourier_terms_3, temp_forecast_3$mean))

#forecast with ARIMA_fit_XREG
ARIMA_Four_forecast_XREG_3<-forecast(ARIMA_Four_fit_XREG_3,
                                     xreg=xreg_matrix_3,
                                     h=12)
```


```{r Neural Network}
#p=1, P=0 because seasonal=FALSE

#K=c(2)
NN_fit_1<-nnetar(ts_training,
                 p=1,
                 P=0,
                 xreg=fourier(ts_training,K=c(2)))

NN_forecast_1<-forecast(NN_fit_1,
                        xreg=fourier(ts_training,K=c(2),h=12), 
                        h=12)

#K=c(4)
NN_fit_2<-nnetar(ts_training,
                 p=1,
                 P=0,
                 xreg=fourier(ts_training,K=c(4)))

NN_forecast_2<-forecast(NN_fit_2,
                        xreg=fourier(ts_training,K=c(4),h=12), 
                        h=12)

#K=c(6)
NN_fit_3<-nnetar(ts_training,
                 p=1,
                 P=0,
                 xreg=fourier(ts_training,K=c(6)))

NN_forecast_3<-forecast(NN_fit_3,
                        xreg=fourier(ts_training,K=c(6),h=12), 
                        h=12)
```


```{r Plot Forecast Results}
#forecast period 
forecast_start<-start(ARIMA_Four_forecast_1$mean)
forecast_end<-end(ARIMA_Four_forecast_1$mean)
ts_forecast<-window(ts_water_monthly, start=forecast_start, end=forecast_end)

#plot forecasting result

#K=c(2)
autoplot(ts_forecast)+
  autolayer(NN_forecast_1, series="Neural Network")+
  autolayer(ARIMA_Four_forecast_1, series="ARIMA Fourier",PI=FALSE)+
  autolayer(ETS_fit,series="STL+ETS",PI=FALSE)+
  autolayer(ARIMA_Four_forecast_XREG_1, series="ARIMA Fourier XREG",PI=FALSE)
  
#K=c(4)
autoplot(ts_forecast)+
  autolayer(ETS_fit,series="STL+ETS",PI=FALSE)+
  autolayer(ARIMA_Four_forecast_2, series="ARIMA Fourier",PI=FALSE)+
  autolayer(ARIMA_Four_forecast_XREG_2, series="ARIMA Fourier XREG",PI=FALSE)+
  autolayer(NN_forecast_2, series="Neural Network")

#K=c(3)
autoplot(ts_forecast)+
  autolayer(ETS_fit,series="STL+ETS",PI=FALSE)+
  autolayer(ARIMA_Four_forecast_3, series="ARIMA Fourier",PI=FALSE)+
  autolayer(ARIMA_Four_forecast_XREG_3, series="ARIMA Fourier XREG",PI=FALSE)+
  autolayer(NN_forecast_3, series="Neural Network")
```

```{r Model Residuals}
resi_ETS<-checkresiduals(ETS_fit)
resi_ARIMA_Four_1<-checkresiduals(ARIMA_Four_forecast_1)
resi_ARIMA_Four_2<-checkresiduals(ARIMA_Four_forecast_2)
resi_ARIMA_Four_3<-checkresiduals(ARIMA_Four_forecast_3)
resi_ARIMA_Four_XREG_1<-checkresiduals(ARIMA_Four_forecast_XREG_1)
resi_ARIMA_Four_XREG_2<-checkresiduals(ARIMA_Four_forecast_XREG_2)
resi_ARIMA_Four_XREG_3<-checkresiduals(ARIMA_Four_forecast_XREG_3)
resi_NN_forecast_1<-checkresiduals(NN_forecast_1)
resi_NN_forecast_2<-checkresiduals(NN_forecast_2)
resi_NN_forecast_3<-checkresiduals(NN_forecast_3)
```

```{r Accuracy}
#Model1:ETS
scores_ETS<-accuracy(ETS_fit$mean,ts_testing)

#Model2: ARIMA + Fourier, K=c(2) 
scores_ARIMA_Four_forecast_1<-accuracy(ARIMA_Four_forecast_1$mean,ts_testing)

#Model3: ARIMA + Fourier, K=c(4)
scores_ARIMA_Four_forecast_2<-accuracy(ARIMA_Four_forecast_2$mean,ts_testing)

#Model4: ARIMA + Fourier, K=c(6)
scores_ARIMA_Four_forecast_3<-accuracy(ARIMA_Four_forecast_3$mean,ts_testing)

#Model5: Neural network, K=c(2) 
scores_NN_1<-accuracy(NN_forecast_1$mean,ts_testing)

#Model6: Neural network, K=c(4)
scores_NN_2<-accuracy(NN_forecast_2$mean,ts_testing)

#Model7: Neural network, K=c(6)
scores_NN_3<-accuracy(NN_forecast_3$mean,ts_testing)

#Model8: ARIMA + Fourier + XREG, K=c(2) 
scores_ARIMA_Four_XREG_1<-accuracy(ARIMA_Four_forecast_XREG_1$mean,ts_testing)

#Model8: ARIMA + Fourier + XREG, K=c(4) 
scores_ARIMA_Four_XREG_2<-accuracy(ARIMA_Four_forecast_XREG_2$mean,ts_testing)

#Model9: ARIMA + Fourier + XREG, K=c(6)
scores_ARIMA_Four_XREG_3<-accuracy(ARIMA_Four_forecast_XREG_3$mean,ts_testing)

#create a data frame to store the scores 
scores<-as.data.frame(rbind(scores_ETS,
                            scores_ARIMA_Four_forecast_1,
                            scores_ARIMA_Four_forecast_2,
                            scores_ARIMA_Four_forecast_3,
                            scores_ARIMA_Four_XREG_1,
                            scores_ARIMA_Four_XREG_2,
                            scores_ARIMA_Four_XREG_3,
                            scores_NN_1,
                            scores_NN_2,
                            scores_NN_3))

scores_NN_all<-as.data.frame(rbind(
                            scores_NN_1,
                            scores_NN_2,
                            scores_NN_3))
row.names(scores)<-c("ETS",
                     "ARIMA+Fourier, K=c(2)",
                     "ARIMA+Fourier, K=c(4)",
                     "ARIMA+Fourier, K=c(6)",
                     "ARIMA+Fourier+XREG, K=c(2)",
                     "ARIMA+Fourier+XREG, K=c(4)",
                     "ARIMA+Fourier+XREG, K=c(6)",
                     "NN, K=c(2)",
                     "NN, K=c(4)",
                     "NN, K=c(6)")

row.names(scores_NN_all)<-c(
                     "NN, K=c(2)",
                     "NN, K=c(4)",
                     "NN, K=c(6)")

#create a comparable table 
kbl(scores, 
    caption = "Forecast Accuracy for Electricity Demand",
    digits = array(5,ncol(scores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position")

kbl(scores_NN_all, 
    caption = "Forecast Accuracy for Electricity Demand",
    digits = array(5,ncol(scores_NN_all))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position")

#RMSE and MAPE
#NN, K=c(2) has the best performance
```